name: php-pecl-imagick
profiles:
  php54w:
    define:
      basepkg: php54w
  php55w:
    define:
      basepkg: php55w
  php56w:
    define:
      basepkg: php56w
  php70w:
    define:
      basepkg: php70w
  php71w:
    define:
      basepkg: php71w
builds:
  webtatic-el7:
    target: el7-development
    arch: [x86_64]
    profiles:
      - php54w
      - php55w
      - php56w
      - php70w
      - php71w
  webtatic-el6:
    target: el6-development
    arch: [x86_64, i386]
    profiles:
      - php54w
      - php55w
      - php56w
      - php70w
      - php71w
